// Generated by gencpp from file ur_dashboard_msgs/IsInRemoteControl.msg
// DO NOT EDIT!


#ifndef UR_DASHBOARD_MSGS_MESSAGE_ISINREMOTECONTROL_H
#define UR_DASHBOARD_MSGS_MESSAGE_ISINREMOTECONTROL_H

#include <ros/service_traits.h>


#include <ur_dashboard_msgs/IsInRemoteControlRequest.h>
#include <ur_dashboard_msgs/IsInRemoteControlResponse.h>


namespace ur_dashboard_msgs
{

struct IsInRemoteControl
{

typedef IsInRemoteControlRequest Request;
typedef IsInRemoteControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsInRemoteControl
} // namespace ur_dashboard_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_dashboard_msgs::IsInRemoteControl > {
  static const char* value()
  {
    return "032fdd19f824627299e7ba024ba3c0bc";
  }

  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControl&) { return value(); }
};

template<>
struct DataType< ::ur_dashboard_msgs::IsInRemoteControl > {
  static const char* value()
  {
    return "ur_dashboard_msgs/IsInRemoteControl";
  }

  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControl&) { return value(); }
};


// service_traits::MD5Sum< ::ur_dashboard_msgs::IsInRemoteControlRequest> should match
// service_traits::MD5Sum< ::ur_dashboard_msgs::IsInRemoteControl >
template<>
struct MD5Sum< ::ur_dashboard_msgs::IsInRemoteControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::IsInRemoteControl >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::IsInRemoteControlRequest> should match
// service_traits::DataType< ::ur_dashboard_msgs::IsInRemoteControl >
template<>
struct DataType< ::ur_dashboard_msgs::IsInRemoteControlRequest>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::IsInRemoteControl >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_dashboard_msgs::IsInRemoteControlResponse> should match
// service_traits::MD5Sum< ::ur_dashboard_msgs::IsInRemoteControl >
template<>
struct MD5Sum< ::ur_dashboard_msgs::IsInRemoteControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_dashboard_msgs::IsInRemoteControl >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_dashboard_msgs::IsInRemoteControlResponse> should match
// service_traits::DataType< ::ur_dashboard_msgs::IsInRemoteControl >
template<>
struct DataType< ::ur_dashboard_msgs::IsInRemoteControlResponse>
{
  static const char* value()
  {
    return DataType< ::ur_dashboard_msgs::IsInRemoteControl >::value();
  }
  static const char* value(const ::ur_dashboard_msgs::IsInRemoteControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_DASHBOARD_MSGS_MESSAGE_ISINREMOTECONTROL_H
